openapi: 3.0.3
info:
  title: OpenAPI definition
  version: v0.1
servers:
  - url: http://localhost:8082
    description: Generated server url
paths:
  /api/v1/autotransport/transaction/sales?saleType=[saleType]:
    get:
      tags:
        - sale-handler
      operationId: getSales
      responses:
        '404':
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ResponseError'
        '500':
          description: Internal Server Error
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ResponseError'
        '403':
          description: Forbidden
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ResponseError'
        '401':
          description: Unauthorized
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ResponseError'
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ResponseError'
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Sale'
    post:
      tags:
        - sale-handler
      operationId: createSale
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Sale'
        required: true
      responses:
        '404':
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ResponseError'
        '403':
          description: Forbidden
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ResponseError'
        '500':
          description: Internal Server Error
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ResponseError'
        '401':
          description: Unauthorized
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ResponseError'
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ResponseError'
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Sale'
    put:
      tags:
        - sale-handler
      operationId: updateSale
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Sale'
        required: true
      responses:
        '404':
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ResponseError'
        '403':
          description: Forbidden
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ResponseError'
        '500':
          description: Internal Server Error
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ResponseError'
        '401':
          description: Unauthorized
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ResponseError'
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ResponseError'
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Sale'
  /api/v1/autotransport/transaction/sales/{saleId}:
    get:
      tags:
        - sale-handler
      operationId: getSale
      parameters:
        - name: saleId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '404':
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ResponseError'
        '500':
          description: Internal Server Error
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ResponseError'
        '403':
          description: Forbidden
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ResponseError'
        '401':
          description: Unauthorized
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ResponseError'
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ResponseError'
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Sale'
  /api/v1/autotransport/transaction/sales/customer/{customerId}:
    get:
      tags:
        - customer-sales-handler
      operationId: getCustomerSales
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '404':
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ResponseError'
        '500':
          description: Internal Server Error
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ResponseError'
        '403':
          description: Forbidden
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ResponseError'
        '401':
          description: Unauthorized
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ResponseError'
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ResponseError'
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Sale'
  /api/v1/autotransport/transaction/sales/customer/{customerId}/sale/{saleId}:
    get:
      tags:
        - customer-sale-handler
      operationId: getCustomerSale
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: saleId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '404':
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ResponseError'
        '500':
          description: Internal Server Error
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ResponseError'
        '403':
          description: Forbidden
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ResponseError'
        '401':
          description: Unauthorized
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ResponseError'
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ResponseError'
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Sale'

##############################
components:
  schemas:
    ResponseError:
      type: object
      properties:
        status:
          type: string
          enum:
            - 100 CONTINUE
            - 101 SWITCHING_PROTOCOLS
            - 102 PROCESSING
            - 103 CHECKPOINT
            - 200 OK
            - 201 CREATED
            - 202 ACCEPTED
            - 203 NON_AUTHORITATIVE_INFORMATION
            - 204 NO_CONTENT
            - 205 RESET_CONTENT
            - 206 PARTIAL_CONTENT
            - 207 MULTI_STATUS
            - 208 ALREADY_REPORTED
            - 226 IM_USED
            - 300 MULTIPLE_CHOICES
            - 301 MOVED_PERMANENTLY
            - 302 FOUND
            - 302 MOVED_TEMPORARILY
            - 303 SEE_OTHER
            - 304 NOT_MODIFIED
            - 305 USE_PROXY
            - 307 TEMPORARY_REDIRECT
            - 308 PERMANENT_REDIRECT
            - 400 BAD_REQUEST
            - 401 UNAUTHORIZED
            - 402 PAYMENT_REQUIRED
            - 403 FORBIDDEN
            - 404 NOT_FOUND
            - 405 METHOD_NOT_ALLOWED
            - 406 NOT_ACCEPTABLE
            - 407 PROXY_AUTHENTICATION_REQUIRED
            - 408 REQUEST_TIMEOUT
            - 409 CONFLICT
            - 410 GONE
            - 411 LENGTH_REQUIRED
            - 412 PRECONDITION_FAILED
            - 413 PAYLOAD_TOO_LARGE
            - 413 REQUEST_ENTITY_TOO_LARGE
            - 414 URI_TOO_LONG
            - 414 REQUEST_URI_TOO_LONG
            - 415 UNSUPPORTED_MEDIA_TYPE
            - 416 REQUESTED_RANGE_NOT_SATISFIABLE
            - 417 EXPECTATION_FAILED
            - 418 I_AM_A_TEAPOT
            - 419 INSUFFICIENT_SPACE_ON_RESOURCE
            - 420 METHOD_FAILURE
            - 421 DESTINATION_LOCKED
            - 422 UNPROCESSABLE_ENTITY
            - 423 LOCKED
            - 424 FAILED_DEPENDENCY
            - 425 TOO_EARLY
            - 426 UPGRADE_REQUIRED
            - 428 PRECONDITION_REQUIRED
            - 429 TOO_MANY_REQUESTS
            - 431 REQUEST_HEADER_FIELDS_TOO_LARGE
            - 451 UNAVAILABLE_FOR_LEGAL_REASONS
            - 500 INTERNAL_SERVER_ERROR
            - 501 NOT_IMPLEMENTED
            - 502 BAD_GATEWAY
            - 503 SERVICE_UNAVAILABLE
            - 504 GATEWAY_TIMEOUT
            - 505 HTTP_VERSION_NOT_SUPPORTED
            - 506 VARIANT_ALSO_NEGOTIATES
            - 507 INSUFFICIENT_STORAGE
            - 508 LOOP_DETECTED
            - 509 BANDWIDTH_LIMIT_EXCEEDED
            - 510 NOT_EXTENDED
            - 511 NETWORK_AUTHENTICATION_REQUIRED
        message:
          type: string
        errors:
          type: array
          items:
            type: string
        url:
          type: string
    Sale:
      required: [ isInsured ]
      type: object
      properties:
        saleId:
          type: integer
          format: int64
        saleType:
          type: string
          pattern: '^[O|Q]$'
        customerId:
          type: integer
          format: int64
        salesNumber:
          description: the number that is display on the ticket to identify the sales
          type: integer
        shipper:
          $ref: '#/components/schemas/SaleAddress'
        consignee:
          $ref: '#/components/schemas/SaleAddress'
        shipmentDetails:
          $ref: '#/components/schemas/ShipmentDetails'
        isInsured:
          type: boolean
        insurance:
          $ref: '#/components/schemas/Insurance'
        customBroker:
          type: integer
          format: int64
        shipmentRates:
          type: array
          items:
            $ref: '#/components/schemas/ShipmentRate'
    SaleAddress:
      required:
        [ address, fromDate, toDate, locationType, phone, email, date ]
      type: object
      properties:
        saleAddressId:
          type: integer
          format: int64
        address:
          type: integer
          format: int64
        fromDate:
          type: string
          format: date
        toDate:
          type: string
          format: date
        locationType:
          $ref: '#/components/schemas/LocationType'
        contact:
          type: integer
          format: int64
        date:
          type: string
          format: date
        readyTime:
          type: string
        closeTime:
          type: string
        additionnalServices:
          type: array
          items:
            $ref: '#/components/schemas/ChargeType'
        coordinate:
          type: integer
          format: int64
    ChargeType:
      type: string
      enum:
        - APP
        - LFT
        - INSD
        - DRS
        - WGV
        - ACC
        - RES
        - JOB
        - TRDS
        - INSE
        - INSS
        - APPF
        - LFTF
        - INSF
        - RESD
        - FLS
        - WTIM
        - MP
        - MD
        - AHP
        - AHD
        - TONU
        - HZMT
        - TMPC
        - ISW
        - BISP
        - STRG
    ShipmentDetails:
      required: [ numberPieces, shipmentType, packageCaracteristic, isFreezeProtect, isTempControl, docOnly, isStackable ]
      type: object
      properties:
        shipmentDetailsId:
          type: integer
          format: int64
        numberPieces:
          type: integer
          format: int32
        totalVolume:
          type: number
        totalChargeableWeight:
          type: number
        shipmentType:
          $ref: '#/components/schemas/ShipmentCategory'
        packageCaracteristic:
          type: array
          items:
            $ref: '#/components/schemas/PackageCaracteristic'
        isFreezeProtect:
          type: boolean
        isTempControl:
          type: boolean
        isStackable:
          type: boolean
        tempUnit:
          $ref: '#/components/schemas/Temperature'
        tempMin:
          type: integer
          format: int32
        tempMax:
          type: integer
          format: int32
        docOnly:
          type: boolean
    PackageCaracteristic:
      required: [ numberPkg, description, length, width, height, weight, hsCode, freightClass, nmfc, isHazMat, numberPieces ]
      type: object
      properties:
        packageCaracteristicId:
          type: integer
          format: int64
        numberPkg:
          type: integer
        description:
          type: string
        length:
          type: integer
          format: int32
        width:
          type: integer
          format: int32
        height:
          type: integer
          format: int32
        weight:
          type: number
        hsCode:
          type: string
          pattern: '^[0-9]{0,10}'
        nmfc:
          type: string
          pattern: '^[0-9]{0,6}'
        freightClass:
          type: string
          pattern: '^[0-9]{0,3}'
        sub:
          type: string
          pattern: '^[0-9]{0,1}'
        hazMat:
          $ref: '#/components/schemas/HazMat'
        emergencyTel:
          type: string
          maxLength: 10
          pattern: '^[0-9]{10}$'
        emergencyContact:
          type: string
          maxLength: 50
        numberPieces:
          type: integer
          format: int32
        isHazMat:
          type: boolean
    Temperature:
      type: string
      enum:
        - F
        - C
    LocationType:
      type: string
      enum:
        - BUS
        - RES_APP
        - RES_HOU
        - OTR_JS
        - OTR_CC
        - OTR_OB
        - OTR_HTL
        - OTR_SHL
    ShipmentCategory:
      type: string
      enum:
        - LTR #letter
        - PCK #pack
        - PCL #parcel
        - SKD #Palet / skid
        - CRT #Crate
        - BDL #Bundle
        - RLL #Roll
        - FLL #Floor loaded
        - FSD #Full truck palet
        - FFL #Full truck floor
    HazMat:
      type: object
      properties:
        hazmatId:
          type: integer
          format: int64
        hazmatClass:
          type: string
        hazmatSubClass:
          type: string
        un:
          type: string
        packageGroup:
          type: string
    Insurance:
      type: object
      properties:
        insuranceId:
          type: integer
          format: int64
        totalCostValue:
          type: number
        currency:
          type: string
        insuranceType:
          type: string
    ShipmentRate:
      type: object
      properties:
        shipmentRateId:
          type: integer
          format: int64
        price:
          description: Price of the rate - all triprate price combine
          type: number
        baseCharge:
          description: price of the base charge - all triprate base charge combine
          type: number
        surcharges:
          description: price of the surcharge - all triprate surcharge combine
          type: number
        rateStatus:
          $ref: '#/components/schemas/RateStatus'
        tripRates:
          type: array
          items:
            $ref: '#/components/schemas/TripRate'
    TripRate:
      type: object
      properties:
        tripRateId:
          type: integer
          format: int64
        vendorId:
          type: integer
          format: int64
        bidOrderCenterId:
          type: integer
          format: int64
        baseCharge:
          description: price of the base charge for a specific vendor/trip
          type: number
        surcharges:
          description: price of the surcharge for a specific vendor/trip
          type: number
        price:
          description: total price for a specific vendor/trip
          type: number
        createdTimestamp:
          description: timestamp of the creation of the trip
          type: string
          format: date-time
        updateTimestamp:
          description: timestamp of the last update of the trip
          type: string
          format: date-time
        rateStatus:
          $ref: '#/components/schemas/RateStatus'
        shipper:
          $ref: '#/components/schemas/SaleAddress'
        consignee:
          $ref: '#/components/schemas/SaleAddress'
        shipmentDetails:
          $ref: '#/components/schemas/ShipmentDetails'
    RateStatus:
      type: string
      enum:
        - REQUESTED # Rate requested to the vendor
        - REJECTED # Customer rejected the rate
        - BIDDED # Vendor bidded on the rate
        - READY # All vendors rate are bidded and price ready to display.
        - EXPIRED # Rate is expired.
        - ACCEPTED # Rate accepted by customer

